/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class net_bc100dev_commons_Terminal */

#ifndef _Included_net_bc100dev_commons_Terminal
#define _Included_net_bc100dev_commons_Terminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bc100dev_commons_Terminal
 * Method:    windowLines
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bc100dev_commons_Terminal_windowLines
  (JNIEnv *, jclass);

/*
 * Class:     net_bc100dev_commons_Terminal
 * Method:    windowColumns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bc100dev_commons_Terminal_windowColumns
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
