/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class net_bc100dev_osintgram4j_cmd_AppRuntime */

#ifndef _Included_net_bc100dev_osintgram4j_cmd_AppRuntime
#define _Included_net_bc100dev_osintgram4j_cmd_AppRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bc100dev_osintgram4j_cmd_AppRuntime
 * Method:    sysTotalMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bc100dev_osintgram4j_cmd_AppRuntime_sysTotalMemory
  (JNIEnv *, jclass);

/*
 * Class:     net_bc100dev_osintgram4j_cmd_AppRuntime
 * Method:    sysAvailableMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bc100dev_osintgram4j_cmd_AppRuntime_sysAvailableMemory
  (JNIEnv *, jclass);

/*
 * Class:     net_bc100dev_osintgram4j_cmd_AppRuntime
 * Method:    sysFreeMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bc100dev_osintgram4j_cmd_AppRuntime_sysFreeMemory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
