/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class net_bc100dev_commons_utils_io_UserIO */

#ifndef _Included_net_bc100dev_commons_utils_io_UserIO
#define _Included_net_bc100dev_commons_utils_io_UserIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bc100dev_commons_utils_io_UserIO
 * Method:    getGid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bc100dev_commons_utils_io_UserIO_getGid
        (JNIEnv *, jclass);

/*
 * Class:     net_bc100dev_commons_utils_io_UserIO
 * Method:    getUid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_bc100dev_commons_utils_io_UserIO_getUid
        (JNIEnv *, jclass);

/*
 * Class:     net_bc100dev_commons_utils_io_UserIO
 * Method:    setUid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bc100dev_commons_utils_io_UserIO_setUid
        (JNIEnv *, jclass, jint);

/*
 * Class:     net_bc100dev_commons_utils_io_UserIO
 * Method:    setGid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_bc100dev_commons_utils_io_UserIO_setGid
        (JNIEnv *, jclass, jint);

/*
 * Class:     net_bc100dev_commons_utils_io_UserIO
 * Method:    nIsAdmin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_bc100dev_commons_utils_io_UserIO_nIsAdmin
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
